export { userIsLogged } from "./auth/auth";;
export { User } from "./database/models/User";
export { dataBase } from "./database/database";
export { setSessionValue,deleteSessionValue } from "./sessions/secureset";
export { getSessionValue } from "./sessions/secureget";
export { checkUserPassword } from "./users/users";
export { WebSocketAuth } from "./database/models/WSAuth";
export { checkWSAuthToken } from "./wsauth/wsauth";
import ExpressServer from "./expressServer";
export default ExpressServer;
const e=new ExpressServer();
e.initAuthSystem();
e.initWSAuthSystem();
e.listen(3069);